project:
  type: website

website:
  title: "bootstrap_quarto_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: theme.scss
    css: styles.css

editor: visual

